---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/case-studies
  label: Case studies
  create: all
  match: "**/*"
upload_dir: static/img
public_path: static/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
